In [1]:
z=""
for i in range(1,101):
    if i%3==0:
        z="Fizz"
    if i%5==0:
        z=z+"Buzz"
    if z<>"":
        print z
    else:
        print i
    z=""

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [2]:
x=[0,1]
z=0
for i in range(2,100):
    x.append(x[i-1]+x[i-2])
    z=i
print x[z]

x=0
y=1
z=0
for i in range(2,100):
    z=x+y
    x=y
    y=z
print z


218922995834555169026
218922995834555169026


In [3]:
x=[1,6,1,6,8,9,0,4,6,8,9,4,3,6,8,0,12,8,23,7,6,34,45,3,34,5,56,3,2,5,4,32,42,53,35,24,65,7,89,37,35,5,17,28,59,6,85,23]

def qsort(myx):
    x=[]
    y=[]
    z=[]
    for i in myx:
        if i<myx[0]: x.append(i)
        elif i==myx[0]: y.append(i)
        else: z.append(i)
    if len(x)>1: x=qsort(x)
    if len(z)>1: z=qsort(z)
    return x+y+z

print qsort(x)

quicksort = lambda seq: [] if not seq else quicksort(filter(lambda n: n<=seq[0], seq[1:]))+[seq[0]]+quicksort(filter(lambda n: n>seq[0], seq[1:]))
print quicksort(x)

[0, 0, 1, 1, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 8, 8, 8, 8, 9, 9, 12, 17, 23, 23, 24, 28, 32, 34, 34, 35, 35, 37, 42, 45, 53, 56, 59, 65, 85, 89]
[0, 0, 1, 1, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 8, 8, 8, 8, 9, 9, 12, 17, 23, 23, 24, 28, 32, 34, 34, 35, 35, 37, 42, 45, 53, 56, 59, 65, 85, 89]


In [ ]:
def myfunc (st, en, x=50, endpoint=True, retstep=False):
    z=[]
    z.append(st)
    x1=x-1
    if endpoint: x1=x
    up=(en-st)/(float(x1))
    for i in range(1,x): z.append(z[i-1]+up)
    if retstep: z=(z,up)
    return z
    
print myfunc(2,5,3)
print myfunc(2,5,3,False)
print myfunc(2,5,3,retstep=True)

V = lambda st, en, x=50, endpoint=True, retstep=False: ([st+i*(en-st)/float(x-1+int(endpoint)) for i in range(0,x)],int(retstep)*(en-st)/float(x-1+int(endpoint)))

print V(2,5,3)
print V(2,5,3,False)
print V(2,5,3,retstep=True)

from numpy import *

%timeit a = array( [2,3,4] )

%timeit a = zeros( (3,4) )
a = zeros( (3,4) )
print a

a = array( [[20,30],[40,50]] )
b = array( [[1,2],[3,4]] )
c = a-b
%timeit c=a-b
print a
print b
print c

a = array([[1,0],[0,1]])
b = array([[2,3],[4,5]])
c = a*b
print a
print b
print c
%timeit c=a*b

a = array([[0,1],[0,1]])
b = array([[2,3],[4,5]])
c = dot(a,b)
print a
print b
print c
print dot(a,b)
%timeit c = dot(a,b)

%timeit a = random.random((2,3))
a = random.random((2,3))
%timeit a.sum()
a.sum()
print a
print a.sum()
print a.min(axis=1)
print a.min(axis=0)

[2, 3.0, 4.0]
[2, 3.5, 5.0]
([2, 3.0, 4.0], 1.0)
([2.0, 3.0, 4.0], 0.0)
([2.0, 3.5, 5.0], 0.0)
([2.0, 3.0, 4.0], 1.0)
The slowest run took 6.89 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.17 µs per loop
The slowest run took 10.94 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 489 ns per loop
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
The slowest run took 10.01 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 668 ns per loop
[[20 30]
 [40 50]]
[[1 2]
 [3 4]]
[[19 28]
 [37 46]]
[[1 0]
 [0 1]]
[[2 3]
 [4 5]]
[[2 0]
 [0 5]]
The slowest run took 7.33 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 669 ns per loop
[[0 1]
 [0 1]]
[[2 3]
 [4 5]]
[[4 5]
 [4 5]]
[[4 5]
 [4 5]]
