In [37]:
def myfunc (st, en, x=50, endpoint=True, retstep=False):
    z=[]
    z.append(st)
    x1=x-1
    if endpoint: x1=x
    up=(en-st)/(float(x1))
    for i in range(1,x): z.append(z[i-1]+up)
    if retstep: z=(z,up)
    return z
    
print myfunc(2,5,3)
print myfunc(2,5,3,False)
print myfunc(2,5,3,retstep=True)

[2, 3.0, 4.0]
[2, 3.5, 5.0]
([2, 3.0, 4.0], 1.0)


In [35]:
V = lambda st, en, x=50, endpoint=True, retstep=False: ([st+i*(en-st)/float(x-1+int(endpoint)) for i in range(0,x)],int(retstep)*(en-st)/float(x-1+int(endpoint)))

print V(2,5,3)
print V(2,5,3,False)
print V(2,5,3,retstep=True)

([2.0, 3.0, 4.0], 0.0)
([2.0, 3.5, 5.0], 0.0)
([2.0, 3.0, 4.0], 1.0)


In [38]:
from numpy import *

%timeit a = array( [2,3,4] )

The slowest run took 7.47 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.19 µs per loop


In [40]:
 %timeit a = zeros( (3,4) )
a = zeros( (3,4) )
print a

The slowest run took 22.53 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 495 ns per loop
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [47]:
a = array( [[20,30],[40,50]] )
b = array( [[1,2],[3,4]] )
c = a-b
%timeit c=a-b
print a
print b
print c

The slowest run took 18.23 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 660 ns per loop
[[20 30]
 [40 50]]
[[1 2]
 [3 4]]
[[19 28]
 [37 46]]


In [43]:
a = array([[1,0],[0,1]])
b = array([[2,3],[4,5]])
c = a*b
print a
print b
print c
%timeit c=a*b

[[1 0]
 [0 1]]
[[2 3]
 [4 5]]
[[2 0]
 [0 5]]
The slowest run took 22.14 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 685 ns per loop


In [55]:
a = array([[0,1],[0,1]])
b = array([[2,3],[4,5]])
c = dot(a,b)
print a
print b
print c
print dot(a,b)
%timeit c = dot(a,b)

[[0 1]
 [0 1]]
[[2 3]
 [4 5]]
[[4 5]
 [4 5]]
[[4 5]
 [4 5]]
The slowest run took 9.55 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.12 µs per loop


In [59]:
%timeit a = random.random((2,3))
a = random.random((2,3))
%timeit a.sum()
a.sum()
print a
print a.sum()
print a.min(axis=1)
print a.min(axis=0)

The slowest run took 12.21 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.28 µs per loop
The slowest run took 8.90 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.46 µs per loop
[[ 0.6843956   0.49940657  0.91365148]
 [ 0.04384684  0.7381255   0.34952776]]
3.22895374784
[ 0.49940657  0.04384684]
[ 0.04384684  0.49940657  0.34952776]
